### ISSUE TITLE
hbase failure

### ISSUE THREAD

**Issue by poneill00** [Cascading/vagrant-cascading-hadoop-cluster#12]
hbase installation requires verify tarball resource which is not present

**Comment by fs111** [comment]
Could you paste the error that you get here? Thanks!

**Comment by poneill00** [comment]
I've been hacking, but let me try to get it back
I think its basically a knock on from commenting out verify_tarball resource in hadoop/init.pp

**Comment by poneill00** [comment]
DEBUG ssh: stderr: Could not find dependency Exec[verify_tarball] for Exec[unpack_hbase] at /tmp/vagrant-puppet-1/modules-0/hbase/manifests/init.pp:25
 INFO interface: info: Could not find dependency Exec[verify_tarball] for Exec[unpack_hbase] at /tmp/vagrant-puppet-1/modules-0/hbase/manifests/init.pp:25
 INFO interface: info: ==> hadoop1: Could not find dependency Exec[verify_tarball] for Exec[unpack_hbase] at /tmp/vagrant-puppet-1/modules-0/hbase/manifests/init.pp:25

**Comment by fs111** [comment]
I just pushed out a fix. Thanks for reporting.
