### ISSUE TITLE
Vagrant up not working on Windows 7 installation

### ISSUE THREAD

**Issue by reddy6ue** [Cascading/vagrant-cascading-hadoop-cluster#15]
Log attached.

Bringing machine 'hadoop1' up with 'virtualbox' provider...
Bringing machine 'hadoop2' up with 'virtualbox' provider...
Bringing machine 'hadoop3' up with 'virtualbox' provider...
Bringing machine 'master' up with 'virtualbox' provider...
==> hadoop1: Importing base box 'cascading-hadoop-base'...
==> hadoop1: Matching MAC address for NAT networking...
==> hadoop1: Setting the name of the VM: vagrant-cascading-hadoop-cluster_hadoop1_1423367959819_34797
==> hadoop1: Clearing any previously set network interfaces...
==> hadoop1: Preparing network interfaces based on configuration...
    hadoop1: Adapter 1: nat
    hadoop1: Adapter 2: hostonly
==> hadoop1: Forwarding ports...
    hadoop1: 22 => 2222 (adapter 1)
==> hadoop1: Running 'pre-boot' VM customizations...
==> hadoop1: Booting VM...
==> hadoop1: Waiting for machine to boot. This may take a few minutes...
    hadoop1: SSH address: 127.0.0.1:2222
    hadoop1: SSH username: vagrant
    hadoop1: SSH auth method: private key
    hadoop1: Warning: Connection timeout. Retrying...
    hadoop1:
    hadoop1: Vagrant insecure key detected. Vagrant will automatically replace
    hadoop1: this with a newly generated keypair for better security.
    hadoop1:
    hadoop1: Inserting generated public key within guest...
    hadoop1: Removing insecure key from the guest if its present...
    hadoop1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> hadoop1: Machine booted and ready!
==> hadoop1: Checking for guest additions in VM...
    hadoop1: The guest additions on this VM do not match the installed version of
    hadoop1: VirtualBox! In most cases this is fine, but in rare cases it can
    hadoop1: prevent things such as shared folders from working properly. If you see
    hadoop1: shared folder errors, please make sure the guest additions within the
    hadoop1: virtual machine match the version of VirtualBox you have installed on
    hadoop1: your host and reload your VM.
    hadoop1:
    hadoop1: Guest Additions Version: 4.2.0
    hadoop1: VirtualBox Version: 4.3
==> hadoop1: Setting hostname...
==> hadoop1: Configuring and enabling network interfaces...
==> hadoop1: Mounting shared folders...
    hadoop1: /vagrant => C:/Projects/crackoo/installs/vagrant-cascading-hadoop-cluster
    hadoop1: /tmp/vagrant-puppet/modules-4fca4bd2748ae13d0d05c7f5ff802769 => C:/Projects/crackoo/installs/vagrant-cascading-hadoop-cluster/modules
    hadoop1: /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513 => C:/Projects/crackoo/installs/vagrant-cascading-hadoop-cluster/manifests
==> hadoop1: Running provisioner: puppet...
==> hadoop1: Running Puppet with datanode.pp...
==> hadoop1: stdin: is not a tty
==> hadoop1: warning: Could not retrieve fact fqdn
==> hadoop1: notice: /Stage[main]/Base/File[/etc/motd]/ensure: defined content as '{md5}0c3e6f224eb6cf6fbff62de3067eaef9'
==> hadoop1: notice: /Stage[main]/Hbase/File[/srv/zookeeper]/ensure: created
==> hadoop1: notice: /Stage[main]/Base/File[/root/.ssh]/ensure: created
==> hadoop1: notice: /Stage[main]/Base/File[/root/.ssh/config]/ensure: defined content as '{md5}880efd788ff2d77bf3989a13a9e0344a'
==> hadoop1: notice: /Stage[main]/Base/File[/root/.ssh/id_rsa.pub]/ensure: defined content as '{md5}622c3becafba74b1f4f1267436cbd28b'
==> hadoop1: notice: /Stage[main]/Base/Ssh_authorized_key[ssh_key]/ensure: created
==> hadoop1: notice: /Stage[main]/Base/Exec[apt-get update]/returns: executed successfully
==> hadoop1: notice: /Stage[main]/Base/Package[openjdk-6-jdk]/ensure: ensure changed 'purged' to 'present'
==> hadoop1: notice: /Stage[main]/Base/File[/root/.ssh/id_rsa]/ensure: defined content as '{md5}a9e4aa776fe92555716b7963488838f6'
==> hadoop1: notice: /Stage[main]/Avahi/Package[avahi-daemon]/ensure: ensure changed 'purged' to 'present'
==> hadoop1: notice: /Stage[main]/Avahi/File[/etc/avahi/avahi-daemon.conf]/content: content changed '{md5}bd8d4eda789abe26c48c1f1f74d19551' to '{md5}e45468ec4a7369471c5101403f5b8f87'
==> hadoop1: notice: /Stage[main]/Avahi/File[/etc/avahi/avahi-daemon.conf]/mode: mode changed '0644' to '0777'
==> hadoop1: notice: /Stage[main]/Hbase/File[/etc/profile.d/hbase-path.sh]/ensure: defined content as '{md5}5fcf2ae92e0f93ced032359ca4b88083'
==> hadoop1: notice: /Stage[main]/Avahi/File[/etc/avahi/hosts]/content: content changed '{md5}186990ae1edac95a88dbef6a36a07716' to '{md5}c90385145a2d6900d7d027bd87cd8ff0'
==> hadoop1: notice: /Stage[main]/Avahi/File[/etc/avahi/hosts]/mode: mode changed '0644' to '0777'
==> hadoop1: notice: /Stage[main]/Avahi/Service[avahi-daemon]: Triggered 'refresh' from 4 events
==> hadoop1: notice: /Stage[main]/Hadoop/File[/etc/profile.d/hadoop-path.sh]/ensure: defined content as '{md5}de0e8f4c7b32f861d3d75eae7786ba92'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/tmp/verifier]/ensure: defined content as '{md5}ee3850511912c0b432c98426be818253'
==> hadoop1: notice: /Stage[main]/Hadoop/Exec[download_grrr]/returns: executed successfully
==> hadoop1: notice: /Stage[main]/Hadoop/Exec[unpack_hadoop]/returns: executed successfully
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/bin/start-all.sh]/ensure: defined content as '{md5}9c53cf01fa353f98dffc39fa30634495'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/bin/prepare-cluster.sh]/ensure: defined content as '{md5}49b2171539abd6dc45bd591eef87c0b9'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/hadoop-env.sh]/content: content changed '{md5}0e1436d2518f41016da667f8a43c1ed7' to '{md5}30c9c1569a8176006c612e
821503e268'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/hadoop-env.sh]/owner: owner changed '10021' to 'vagrant'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/hadoop-env.sh]/group: group changed '10021' to 'root'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/masters]/ensure: defined content as '{md5}6b5b2eacceaea2cb67658abac224233a'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/hdfs-site.xml]/content: content changed '{md5}06f0cc5cad0018c16ef3dcb404efb74e' to '{md5}4ac01efa0c1d42f2a723ae
bbc51e9c7f'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/hdfs-site.xml]/owner: owner changed '10021' to 'vagrant'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/hdfs-site.xml]/group: group changed '10021' to 'root'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/yarn-site.xml]/content: content changed '{md5}f679a7750b76612f7468f61a7c6b75e7' to '{md5}51ef366c9c1d2d01fc096e
f1add1a42e'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/yarn-site.xml]/owner: owner changed '10021' to 'vagrant'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/yarn-site.xml]/group: group changed '10021' to 'root'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/slaves]/content: content changed '{md5}b8419160170a41ae01abab13a3b887df' to '{md5}0ddd3131a9fb114730223d9544585
6af'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/slaves]/owner: owner changed '10021' to 'vagrant'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/slaves]/group: group changed '10021' to 'root'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/yarn-env.sh]/content: content changed '{md5}ff35d7ff15bf26fe2b78faae61a76e28' to '{md5}6c12785897931ac9033547a7
f6060cdf'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/yarn-env.sh]/owner: owner changed '10021' to 'vagrant'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/yarn-env.sh]/group: group changed '10021' to 'root'
==> hadoop1: notice: /Stage[main]/Hadoop/Exec[hadoop_conf_permissions]/returns: executed successfully
==> hadoop1: err: /Stage[main]/Hbase/Exec[unpack_hbase]/returns: change from notrun to 0 failed: tar xf /vagrant/hbase-0.98.9-hadoop2-bin.tar.gz -C /opt returned 2 instead of one of [0]
at /tmp/vagrant-puppet/modules-4fca4bd2748ae13d0d05c7f5ff802769/hbase/manifests/init.pp:24
==> hadoop1: notice: /Stage[main]/Hbase/File[/opt/hbase-0.98.9-hadoop2/conf/hbase-site.xml]: Dependency Exec[unpack_hbase] has failures: true
==> hadoop1: warning: /Stage[main]/Hbase/File[/opt/hbase-0.98.9-hadoop2/conf/hbase-site.xml]: Skipping because of failed dependencies
==> hadoop1: notice: /Stage[main]/Hbase/File[/opt/hbase-0.98.9-hadoop2/conf/regionservers]: Dependency Exec[unpack_hbase] has failures: true
==> hadoop1: warning: /Stage[main]/Hbase/File[/opt/hbase-0.98.9-hadoop2/conf/regionservers]: Skipping because of failed dependencies
==> hadoop1: notice: /Stage[main]/Hbase/File[/opt/hbase-0.98.9-hadoop2/conf/hbase-env.sh]: Dependency Exec[unpack_hbase] has failures: true
==> hadoop1: warning: /Stage[main]/Hbase/File[/opt/hbase-0.98.9-hadoop2/conf/hbase-env.sh]: Skipping because of failed dependencies
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/core-site.xml]/content: content changed '{md5}315d2770c60bc9a0b3c7dc04e41fda76' to '{md5}a10970d7829d67cbe59ddc
94aa8fd0b7'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/core-site.xml]/group: group changed '10021' to 'root'
==> hadoop1: notice: /Stage[main]/Avahi/File[/etc/hosts]/content: content changed '{md5}28728fdc2cb16bf53da7ba1988a7e978' to '{md5}c90385145a2d6900d7d027bd87cd8ff0'
==> hadoop1: notice: /Stage[main]/Avahi/File[/etc/hosts]/mode: mode changed '0644' to '0777'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/etc/hadoop/mapred-site.xml]/ensure: defined content as '{md5}cc11dad8a2e5fbae299f3759da00e427'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/bin/stop-all.sh]/ensure: defined content as '{md5}6e9fea170eeb7d4ec916c3707d16941e'
==> hadoop1: notice: /Stage[main]/Hadoop/Group[hadoop]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/User[hdfs]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/File[/srv/hadoop/]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/File[/srv/hadoop/namenode]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/File[/srv/hadoop/datanode/]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/logs]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/User[yarn]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/logs/yarn]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/User[mapred]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/logs/mapred]/ensure: created
==> hadoop1: notice: /Stage[main]/Hadoop/File[/opt/hadoop-2.5.2/logs/hadoop]/ensure: created
==> hadoop1: notice: Finished catalog run in 186.45 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by sidorovis** [comment]
try this first: https://github.com/Cascading/vagrant-cascading-hadoop-cluster/issues/8

**Comment by fs111** [comment]
It is related to Hbase. They have made a new release and the old one is gone from the mirrors. I updated the project. Please pull in the latest changes and do a vagrant destroy -f && vagrant up That should fix it. If not, please re-open the issue.

**Comment by reddy6ue** [comment]
Confirmed that #8 works. Still curious why the git download works, but the clone doesn't.

**Comment by fs111** [comment]
Try git again, it will work now. See this message:

```
hadoop1: err: /Stage[main]/Hbase/Exec[unpack_hbase]/returns: change from notrun to 0 failed: tar xf /vagrant/hbase-0.98.9-hadoop2-bin.tar.gz -C /opt returned 2 instead of one of [0]
```

That was puppet trying to download and extract an HBase release, which is no longer available on some mirrors. I fixed that b pointing to a newer release.
