### ISSUE TITLE
"wip-2.5" branch contains hadoop 2.2.0, not Hadoop 2.3.0 as mentioned in the readme

### ISSUE THREAD

**Issue by rmetzger** [Cascading/vagrant-cascading-hadoop-cluster#3]
Hi,
As [promised](https://twitter.com/rmetzger_/status/438354989178953729), I tested the stuff in the repository to start a Hadoop 2.3.0 cluster. But there seems to be something wrong.

``` bash
git clone https://github.com/Cascading/vagrant-cascading-hadoop-cluster.git
git checkout wip-2.5
vagrant up
vagrant ssh master
vagrant@master:~$ hadoop version
Hadoop 2.2.0
vagrant@master:~$ ls /opt/
CascadingSDK  hadoop-2.2.0  hbase-0.96.1.1-hadoop2  tools  vagrant_ruby  VBoxGuestAdditions-4.2.0
```

**Comment by fs111** [comment]
Good catch, I forgot to push the change last week, since I waited for the [compat tests](http://www.cascading.org/support/compatibility/) to publish first. I just pushed it out. git pull && vagrant provision should do the trick.
