### ISSUE TITLE
"wip-2.5" branch: YARN NodeManagers do not have correctly configured memory sizes

### ISSUE THREAD

**Issue by rmetzger** [Cascading/vagrant-cascading-hadoop-cluster#4]
The cluster's NodeManager do not have a correctly configured memory sizes in `yarn-site.xml`:

``` xml
  <!--property>
      <name>yarn.nodemanager.resource.memory-mb</name>
      <value>1024</value>
  </property-->
```

This leads to hard-to-find errors since the OOM killer of Linux is shooting the containers and YARN considers the container to have finished regularly.

Is there a reason why the property is commented out?

**Comment by fs111** [comment]
I started with this in the 2.1-beta days and back then setting this would cause no job to start. This might have changed. Can you uncomment it and give it a spin?

**Comment by rmetzger** [comment]
Okay, I'll do it once I'm back home. My laptop is not capable of running 4 virtual machines.

**Comment by fs111** [comment]
Thank you. There is also a new single-node option, in case you missed it: https://github.com/Cascading/vagrant-cascading-hadoop-cluster/tree/wip-2.5#single-node-setup

**Comment by rmetzger** [comment]
Wow, these vagrant VM's are very useful ;)
The single-node one also works very well.

I uncommented it, and everything run smoothly (however, I did not test with MapReduce).

**Comment by fs111** [comment]
fixed and closed
