### ISSUE TITLE
Jobs submit but won't start in HDFS

### ISSUE THREAD

**Issue by derrickpelletier** [Cascading/vagrant-cascading-hadoop-cluster#5]
Whipped up a quick scalding job as a test to just read in a file and write it out, but the job doesn't start.

If I run it in `--local` mode, it runs fine.
When I attempt with `--hdfs` (after putting the file on the hdfs) the job gets submitted, no errors are thrown. The job exists in the job tracker queue as submitted, but it never starts.

Is this normal—maybe I'm missing something to get the job started? I get this behaviour in both the multi and single node variants. Perhaps just something I'm not aware of for using HDFS?

Thanks for your help

**Comment by fs111** [comment]
I just pushed a change that was sitting in my repo for a while, which should fix this. Could you please update your version and restart the cluster to try again? Thx.

**Comment by derrickpelletier** [comment]
Gladly! But which branch? None seem to have a recent commit.

**Comment by fs111** [comment]
Please use the 2.5 branch. The commit is already a few weeks old, I just forgot to push it out. sorry about that.

**Comment by derrickpelletier** [comment]
Looks like it's working, many thanks.
