### ISSUE TITLE
Errors running against Vagrant 1.6.3 / VirtualBox 4.3.12

### ISSUE THREAD

**Issue by brentvukmer** [Cascading/vagrant-cascading-hadoop-cluster#7]
Saw this on my Mac: 
==> hadoop1: notice: /Stage[main]/Base/Package[openjdk-6-jdk]/ensure: ensure changed 'purged' to 'present'
==> hadoop1: notice: /Stage[main]/Base/File[/root/.ssh/id_rsa]/ensure: defined content as '{md5}a9e4aa776fe92555716b7963488838f6'
==> hadoop1: notice: /Stage[main]/Avahi/Package[avahi-daemon]/ensure: ensure changed 'purged' to 'present'
==> hadoop1: notice: /Stage[main]/Avahi/File[/etc/avahi/avahi-daemon.conf]/content: content changed '{md5}bd8d4eda789abe26c48c1f1f74d19551' to '{md5}e45468ec4a7369471c5101403f5b8f87'
==> hadoop1: notice: /Stage[main]/Hbase/File[/etc/profile.d/hbase-path.sh]/ensure: defined content as '{md5}06cf529d2063f3060bfca646dd2d1a18'
==> hadoop1: notice: /Stage[main]/Avahi/File[/etc/avahi/hosts]/content: content changed '{md5}186990ae1edac95a88dbef6a36a07716' to '{md5}c90385145a2d6900d7d027bd87cd8ff0'
==> hadoop1: notice: /Stage[main]/Avahi/Service[avahi-daemon]: Triggered 'refresh' from 2 events
==> hadoop1: notice: /Stage[main]/Hadoop/File[/etc/profile.d/hadoop-path.sh]/ensure: defined content as '{md5}da4327f03f22df21251fece99b4fda68'
==> hadoop1: notice: /Stage[main]/Hadoop/File[/tmp/verifier]/ensure: defined content as '{md5}ee3850511912c0b432c98426be818253'
==> hadoop1: notice: /Stage[main]/Hadoop/Exec[download_grrr]/returns: executed successfully
==> hadoop1: notice: /Stage[main]/Avahi/File[/etc/hosts]/content: content changed '{md5}28728fdc2cb16bf53da7ba1988a7e978' to '{md5}c90385145a2d6900d7d027bd87cd8ff0'
==> hadoop1: err: /Stage[main]/Hadoop/Exec[verify_tarball]/returns: change from notrun to 0 failed: /tmp/verifier /vagrant/hadoop-2.3.0.tar.gz.mds returned 1 instead of one of [0] at /tmp/vagrant-puppet-1/modules-0/hadoop/manifests/init.pp:66
==> hadoop1: notice: /Stage[main]/Hbase/Exec[unpack_hbase]: Dependency Exec[verify_tarball] has failures: true

**Comment by fs111** [comment]
something went wrong with the download of the hadoop tarball. "Dependency Exec[verify_tarball] has failures:". We are downloading the tarball and then checking the md5 sums. Please delete the hadoop-2.3.0.tar.gz   and hadoop-2.3.0.tar.gz.mds files in the local directory and run vagrant provision.

Also, in which area of the world are you? We try to download from a local apache mirror, if we can find one.

**Comment by brentvukmer** [comment]
I'm on Richmond, VA.   Thanks for the pointers, I'll give them a try tonight.

**Comment by fs111** [comment]
can you delete the tarball and the mds file and run "vagrant provision"?

**Comment by brentvukmer** [comment]
Looks like that took care of it.  Thanks for the help!

**Comment by fs111** [comment]
Glad it works now. Closing the issue.
